services:
  facebook-group-poster:
    secrets:
      - facebook_login_email
      - facebook_login_password

  facebook-group-poster-login:
    secrets:
      - facebook_login_email
      - facebook_login_password

secrets:
  facebook_login_email:
    file: ${FACEBOOK_LOGIN_EMAIL_SECRET_FILE}
  facebook_login_password:
    file: ${FACEBOOK_LOGIN_PASSWORD_SECRET_FILE}
